=== WCDave/RocketPlus/Documents/solsys.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="http://solsys" xmlns:ss="http://solsys" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="Planets" type="ss:PlanetsType"/>
	<xs:complexType name="PlanetColorType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="red" type="xs:short" use="optional"/>
				<xs:attribute name="green" type="xs:short" use="optional"/>
				<xs:attribute name="blue" type="xs:short" use="optional"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="PlanetType">
		<xs:sequence>
			<xs:element name="PlanetName" type="xs:string"  />				
			<xs:element name="PlanetColor" type="ss:PlanetColorType"/>
			<xs:element name="TrueAnamoly" type="xs:float"/>
			<xs:element name="PerihelionAngle"  type="xs:float" />
			<xs:element name="Obliquity"  type="xs:float" />
			<xs:element name="RotationalPeriod"  type="xs:float"/>
			<xs:element name="MeanAnamoly0">
				<xs:simpleType>
					<xs:restriction base="xs:float">
						<xs:enumeration value="0.0"/>
						<xs:enumeration value="168.6562"/>
						<xs:enumeration value="48.0052"/>
						<xs:enumeration value="356.047"/>
						<xs:enumeration value="18.6021"/>
						<xs:enumeration value="19.895"/>
						<xs:enumeration value="316.967"/>
						<xs:enumeration value="142.5905"/>
						<xs:enumeration value="260.2471"/>
						<xs:enumeration value="14.704"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="MeanAnamoly" type="xs:float"/>
			<xs:element name="Dm">
				<xs:simpleType>
					<xs:restriction base="xs:float">
						<xs:enumeration value="0.0"/>
						<xs:enumeration value="4.0923343"/>
						<xs:enumeration value="1.6021302"/>
						<xs:enumeration value="0.98560023"/>
						<xs:enumeration value="0.5240208"/>
						<xs:enumeration value="0.08380853"/>
						<xs:enumeration value="0.03344423"/>
						<xs:enumeration value="0.011725806"/>
						<xs:enumeration value="0.005995147"/>
						<xs:enumeration value="0.003975571"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Radius">
				<xs:simpleType>
					<xs:restriction base="xs:float">
						<xs:enumeration value="6.96E8"/>
						<xs:enumeration value="2430000.0"/>
						<xs:enumeration value="6060000.0"/>
						<xs:enumeration value="6370000.0"/>
						<xs:enumeration value="3370000.0"/>
						<xs:enumeration value="6.99E7"/>
						<xs:enumeration value="5.85E7"/>
						<xs:enumeration value="2.33E7"/>
						<xs:enumeration value="2.21E7"/>
						<xs:enumeration value="1500000.0"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Oblateness"  type="xs:float" />
			<xs:element name="ArgOfPerhelion"  type="xs:float"/>
			<xs:element name="Atmo">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="false"/>
						<xs:enumeration value="true"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="SemiMajorAxis">
				<xs:simpleType>
					<xs:restriction base="xs:float">
						<xs:enumeration value="0.0"/>
						<xs:enumeration value="5.7909035E10"/>
						<xs:enumeration value="1.08208628E11"/>
						<xs:enumeration value="1.4959788E11"/>
						<xs:enumeration value="2.27940467E11"/>
						<xs:enumeration value="7.7829184E11"/>
						<xs:enumeration value="1.42937031E12"/>
						<xs:enumeration value="2.86954278E12"/>
						<xs:enumeration value="4.4966515E12"/>
						<xs:enumeration value="5.9063764E12"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Period">
				<xs:simpleType>
					<xs:restriction base="xs:float">
						<xs:enumeration value="0.0"/>
						<xs:enumeration value="1.39354015E16"/>
						<xs:enumeration value="3.55953146E16"/>
						<xs:enumeration value="5.7861297E16"/>
						<xs:enumeration value="1.08825873E17"/>
						<xs:enumeration value="6.8661567E17"/>
						<xs:enumeration value="1.70890193E18"/>
						<xs:enumeration value="4.8609266E18"/>
						<xs:enumeration value="9.535288E18"/>
						<xs:enumeration value="1.4354289E19"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Eccentricity">
				<xs:simpleType>
					<xs:restriction base="xs:float">
						<xs:enumeration value="0.0"/>
						<xs:enumeration value="0.205635"/>
						<xs:enumeration value="0.006773"/>
						<xs:enumeration value="0.016709"/>
						<xs:enumeration value="0.093405"/>
						<xs:enumeration value="0.048498"/>
						<xs:enumeration value="0.055546"/>
						<xs:enumeration value="0.047318"/>
						<xs:enumeration value="0.008606"/>
						<xs:enumeration value="0.248808"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Inclination">
				<xs:simpleType>
					<xs:restriction base="xs:float">
						<xs:enumeration value="0.0"/>
						<xs:enumeration value="7.0047"/>
						<xs:enumeration value="3.3946"/>
						<xs:enumeration value="1.8497"/>
						<xs:enumeration value="1.303"/>
						<xs:enumeration value="2.4886"/>
						<xs:enumeration value="0.7733"/>
						<xs:enumeration value="1.77"/>
						<xs:enumeration value="17.14175"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="AscendingNode">
				<xs:simpleType>
					<xs:restriction base="xs:float">
						<xs:enumeration value="0.0"/>
						<xs:enumeration value="48.3313"/>
						<xs:enumeration value="76.6799"/>
						<xs:enumeration value="49.5574"/>
						<xs:enumeration value="100.4542"/>
						<xs:enumeration value="113.6634"/>
						<xs:enumeration value="74.0005"/>
						<xs:enumeration value="131.7806"/>
						<xs:enumeration value="110.3035"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="EpochLongitude">
				<xs:simpleType>
					<xs:restriction base="xs:float">
						<xs:enumeration value="0.0"/>
						<xs:enumeration value="252.3"/>
						<xs:enumeration value="182.0"/>
						<xs:enumeration value="100.5"/>
						<xs:enumeration value="355.4"/>
						<xs:enumeration value="34.4"/>
						<xs:enumeration value="50.1"/>
						<xs:enumeration value="314.1"/>
						<xs:enumeration value="304.3"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Mass">
				<xs:simpleType>
					<xs:restriction base="xs:float">
						<xs:enumeration value="1.99E30"/>
						<xs:enumeration value="3.18E23"/>
						<xs:enumeration value="4.88E24"/>
						<xs:enumeration value="5.98E24"/>
						<xs:enumeration value="6.42E23"/>
						<xs:enumeration value="1.9E27"/>
						<xs:enumeration value="5.68E26"/>
						<xs:enumeration value="8.68E25"/>
						<xs:enumeration value="1.03E26"/>
						<xs:enumeration value="1.4E22"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="PlanetsType">
		<xs:sequence>
			<xs:element name="Planet" type="ss:PlanetType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== WCDave/RocketPlus/Documents/orbitdata.xml
<?xml version="1.0" encoding="UTF-8"?>
<Planets xmlns="solsys" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="solsys.xsd">
	<Planet>
		<PlanetName>Sun</PlanetName>
		<PlanetColor red="255" green="255" blue="0"/>
		<TrueAnamoly>0.0</TrueAnamoly>
		<PerihelionAngle>0.0</PerihelionAngle>
		<Obliquity>0.0</Obliquity>
		<RotationalPeriod>0.0</RotationalPeriod>
		<MeanAnamoly0>0.0</MeanAnamoly0>
		<MeanAnamoly>0.0</MeanAnamoly>
		<Dm>0.0</Dm>
		<Radius>6.96E8</Radius>
		<Oblateness>0.0</Oblateness>
		<ArgOfPerhelion>0.0</ArgOfPerhelion>
		<Atmo>false</Atmo>
		<SemiMajorAxis>0.0</SemiMajorAxis>
		<Period>0.0</Period>
		<Eccentricity>0.0</Eccentricity>
		<Inclination>0.0</Inclination>
		<AscendingNode>0.0</AscendingNode>
		<EpochLongitude>0.0</EpochLongitude>
		<Mass>1.99E30</Mass>
	</Planet>
	<Planet>
		<PlanetName>Mercury</PlanetName>
		<PlanetColor red="145" green="147" blue="153"/>
		<TrueAnamoly>0.0</TrueAnamoly>
		<PerihelionAngle>77.46</PerihelionAngle>
		<Obliquity>0.1</Obliquity>
		<RotationalPeriod>1407.5</RotationalPeriod>
		<MeanAnamoly0>168.6562</MeanAnamoly0>
		<MeanAnamoly>0.0</MeanAnamoly>
		<Dm>4.0923343</Dm>
		<Radius>2430000.0</Radius>
		<Oblateness>0.0</Oblateness>
		<ArgOfPerhelion>29.128693</ArgOfPerhelion>
		<Atmo>false</Atmo>
		<SemiMajorAxis>5.7909035E10</SemiMajorAxis>
		<Period>1.39354015E16</Period>
		<Eccentricity>0.205635</Eccentricity>
		<Inclination>7.0047</Inclination>
		<AscendingNode>48.3313</AscendingNode>
		<EpochLongitude>252.3</EpochLongitude>
		<Mass>3.18E23</Mass>
	</Planet>
	<Planet>
		<PlanetName>Venus</PlanetName>
		<PlanetColor red="234" green="239" blue="197"/>
		<TrueAnamoly>0.0</TrueAnamoly>
		<PerihelionAngle>131.6</PerihelionAngle>
		<Obliquity>177.4</Obliquity>
		<RotationalPeriod>5832.5</RotationalPeriod>
		<MeanAnamoly0>48.0052</MeanAnamoly0>
		<MeanAnamoly>0.0</MeanAnamoly>
		<Dm>1.6021302</Dm>
		<Radius>6060000.0</Radius>
		<Oblateness>0.0</Oblateness>
		<ArgOfPerhelion>54.920105</ArgOfPerhelion>
		<Atmo>true</Atmo>
		<SemiMajorAxis>1.08208628E11</SemiMajorAxis>
		<Period>3.55953146E16</Period>
		<Eccentricity>0.006773</Eccentricity>
		<Inclination>3.3946</Inclination>
		<AscendingNode>76.6799</AscendingNode>
		<EpochLongitude>182.0</EpochLongitude>
		<Mass>4.88E24</Mass>
	</Planet>
	<Planet>
		<PlanetName>Earth</PlanetName>
		<PlanetColor red="60" green="151" blue="219"/>
		<TrueAnamoly>0.0</TrueAnamoly>
		<PerihelionAngle>102.9</PerihelionAngle>
		<Obliquity>23.439281</Obliquity>
		<RotationalPeriod>23.9345</RotationalPeriod>
		<MeanAnamoly0>356.047</MeanAnamoly0>
		<MeanAnamoly>0.0</MeanAnamoly>
		<Dm>0.98560023</Dm>
		<Radius>6370000.0</Radius>
		<Oblateness>0.0</Oblateness>
		<ArgOfPerhelion>102.899994</ArgOfPerhelion>
		<Atmo>true</Atmo>
		<SemiMajorAxis>1.4959788E11</SemiMajorAxis>
		<Period>5.7861297E16</Period>
		<Eccentricity>0.016709</Eccentricity>
		<Inclination>0.0</Inclination>
		<AscendingNode>0.0</AscendingNode>
		<EpochLongitude>100.5</EpochLongitude>
		<Mass>5.98E24</Mass>
	</Planet>
	<Planet>
		<PlanetName>Mars</PlanetName>
		<PlanetColor red="223" green="126" blue="55"/>
		<TrueAnamoly>0.0</TrueAnamoly>
		<PerihelionAngle>336.1</PerihelionAngle>
		<Obliquity>25.19</Obliquity>
		<RotationalPeriod>24.623</RotationalPeriod>
		<MeanAnamoly0>18.6021</MeanAnamoly0>
		<MeanAnamoly>0.0</MeanAnamoly>
		<Dm>0.5240208</Dm>
		<Radius>3370000.0</Radius>
		<Oblateness>0.0</Oblateness>
		<ArgOfPerhelion>286.5426</ArgOfPerhelion>
		<Atmo>true</Atmo>
		<SemiMajorAxis>2.27940467E11</SemiMajorAxis>
		<Period>1.08825873E17</Period>
		<Eccentricity>0.093405</Eccentricity>
		<Inclination>1.8497</Inclination>
		<AscendingNode>49.5574</AscendingNode>
		<EpochLongitude>355.4</EpochLongitude>
		<Mass>6.42E23</Mass>
	</Planet>
	<Planet>
		<PlanetName>Jupiter</PlanetName>
		<PlanetColor red="239" green="193" blue="160"/>
		<TrueAnamoly>0.0</TrueAnamoly>
		<PerihelionAngle>14.3</PerihelionAngle>
		<Obliquity>3.12</Obliquity>
		<RotationalPeriod>9.925</RotationalPeriod>
		<MeanAnamoly0>19.895</MeanAnamoly0>
		<MeanAnamoly>0.0</MeanAnamoly>
		<Dm>0.08380853</Dm>
		<Radius>6.99E7</Radius>
		<Oblateness>0.05</Oblateness>
		<ArgOfPerhelion>273.8458</ArgOfPerhelion>
		<Atmo>true</Atmo>
		<SemiMajorAxis>7.7829184E11</SemiMajorAxis>
		<Period>6.8661567E17</Period>
		<Eccentricity>0.048498</Eccentricity>
		<Inclination>1.303</Inclination>
		<AscendingNode>100.4542</AscendingNode>
		<EpochLongitude>34.4</EpochLongitude>
		<Mass>1.9E27</Mass>
	</Planet>
	<Planet>
		<PlanetName>Saturn</PlanetName>
		<PlanetColor red="232" green="228" blue="168"/>
		<TrueAnamoly>0.0</TrueAnamoly>
		<PerihelionAngle>93.1</PerihelionAngle>
		<Obliquity>26.73</Obliquity>
		<RotationalPeriod>10.656</RotationalPeriod>
		<MeanAnamoly0>316.967</MeanAnamoly0>
		<MeanAnamoly>0.0</MeanAnamoly>
		<Dm>0.03344423</Dm>
		<Radius>5.85E7</Radius>
		<Oblateness>0.05</Oblateness>
		<ArgOfPerhelion>339.43658</ArgOfPerhelion>
		<Atmo>true</Atmo>
		<SemiMajorAxis>1.42937031E12</SemiMajorAxis>
		<Period>1.70890193E18</Period>
		<Eccentricity>0.055546</Eccentricity>
		<Inclination>2.4886</Inclination>
		<AscendingNode>113.6634</AscendingNode>
		<EpochLongitude>50.1</EpochLongitude>
		<Mass>5.68E26</Mass>
	</Planet>
	<Planet>
		<PlanetName>Uranus</PlanetName>
		<PlanetColor red="182" green="209" blue="218"/>
		<TrueAnamoly>0.0</TrueAnamoly>
		<PerihelionAngle>170.6617</PerihelionAngle>
		<Obliquity>97.86</Obliquity>
		<RotationalPeriod>17.24</RotationalPeriod>
		<MeanAnamoly0>142.5905</MeanAnamoly0>
		<MeanAnamoly>0.0</MeanAnamoly>
		<Dm>0.011725806</Dm>
		<Radius>2.33E7</Radius>
		<Oblateness>0.0</Oblateness>
		<ArgOfPerhelion>96.661194</ArgOfPerhelion>
		<Atmo>true</Atmo>
		<SemiMajorAxis>2.86954278E12</SemiMajorAxis>
		<Period>4.8609266E18</Period>
		<Eccentricity>0.047318</Eccentricity>
		<Inclination>0.7733</Inclination>
		<AscendingNode>74.0005</AscendingNode>
		<EpochLongitude>314.1</EpochLongitude>
		<Mass>8.68E25</Mass>
	</Planet>
	<Planet>
		<PlanetName>Neptune</PlanetName>
		<PlanetColor red="123" green="172" blue="176"/>
		<TrueAnamoly>0.0</TrueAnamoly>
		<PerihelionAngle>48.1</PerihelionAngle>
		<Obliquity>29.56</Obliquity>
		<RotationalPeriod>16.11</RotationalPeriod>
		<MeanAnamoly0>260.2471</MeanAnamoly0>
		<MeanAnamoly>0.0</MeanAnamoly>
		<Dm>0.005995147</Dm>
		<Radius>2.21E7</Radius>
		<Oblateness>0.0</Oblateness>
		<ArgOfPerhelion>276.3194</ArgOfPerhelion>
		<Atmo>true</Atmo>
		<SemiMajorAxis>4.4966515E12</SemiMajorAxis>
		<Period>9.535288E18</Period>
		<Eccentricity>0.008606</Eccentricity>
		<Inclination>1.77</Inclination>
		<AscendingNode>131.7806</AscendingNode>
		<EpochLongitude>304.3</EpochLongitude>
		<Mass>1.03E26</Mass>
	</Planet>
	<Planet>
		<PlanetName>Pluto</PlanetName>
		<PlanetColor red="255" green="255" blue="255"/>
		<TrueAnamoly>0.0</TrueAnamoly>
		<PerihelionAngle>224.0668</PerihelionAngle>
		<Obliquity>119.6</Obliquity>
		<RotationalPeriod>153.29</RotationalPeriod>
		<MeanAnamoly0>14.704</MeanAnamoly0>
		<MeanAnamoly>0.0</MeanAnamoly>
		<Dm>0.003975571</Dm>
		<Radius>1500000.0</Radius>
		<Oblateness>0.0</Oblateness>
		<ArgOfPerhelion>113.763306</ArgOfPerhelion>
		<Atmo>false</Atmo>
		<SemiMajorAxis>5.9063764E12</SemiMajorAxis>
		<Period>1.4354289E19</Period>
		<Eccentricity>0.248808</Eccentricity>
		<Inclination>17.14175</Inclination>
		<AscendingNode>110.3035</AscendingNode>
		<EpochLongitude>0.0</EpochLongitude>
		<Mass>1.4E22</Mass>
	</Planet>
</Planets>
